### ISSUE TITLE
Add Github URL to extension pages

### ISSUE THREAD

**Issue by TotalCaesar659** [erikdesjardins/no-emoji#9]
@erikdesjardins Hello, could you add Github URL to extension pages in [Chrome Web Store](https://chrome.google.com/webstore/detail/no-emoji/obbjmeopodlheliibjoabgbmchpecjaj) and [Mozilla Addons](https://addons.mozilla.org/en-US/firefox/addon/no-emoji/) and write that it's open-source? Somebody when searching open-source extension may not find it.

**Comment by erikdesjardins** [comment]
Added as the "extension website" url

**Comment by TotalCaesar659** [comment]
Thank you!
